name: Deploy rails-room
on:
  push:
    branches: main
jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy to Heroku
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          email: ${{ secrets.HEROKU_EMAIL }}
          dockerfile_name: Dockerfile
          docker_options: "--no-cache"
          process_type: web
